### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [jas-/node-libnmap#54]
Hello,

As a member of the [Node.js Security WG](https://hackerone.com/nodejs-ecosystem)
I would like to draw your attention to a security report that has been made regarding this issue.

I have made attempts to contact the person identified as a maintainer of this package but did not get any answer. What is the best way to reach someone with commit rights over this repo and hopefully npm publishing rights as well, in order to invite them to privately discuss the issue on the HackerOne platform and provide a resolution? 

Thanks,
Liran

References:
* [Node.js Security WG ecosystem vulnerability processes](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md)

**Comment by jas-** [comment]
What package are you referring to? Perhaps the dependency and issue I have raised with the included [cidr-js](https://github.com/krg7880/cidr-js/issues/4) package?

**Comment by lirantal** [comment]
Hi @jas- 
Thanks for the quick reply!

Referring to this library actually. Can you jump in on the HackerOne invite? you should see it in your inbox (or maybe spam folder) ?

**Comment by jas-** [comment]
We can discuss it here.

**Comment by lirantal** [comment]
The purpose of inviting you to discuss the issue in a private forum is to protect users of this library so that we don't disclose the vulnerability without you releasing a fix in time to address the issue and leaving users of this library vulnerable for that period of time until a fix is deployed.

**Comment by jas-** [comment]
Such is a normal notification process for projects and applications that are high impact with regards to dependencies and adoption.

While this project does indeed garner some use. The impact of a security vulnerability, with regards to local or even remote compromise, would be small in numbers.

Perhaps this would seem reckless, but I am all about the open forum and the idea that any users of this project have visibility into any issue so they mitigate it prior to a patch.

**Comment by lirantal** [comment]
Once we resolve the issue reported we will be happily disclosing the report publicly.

**Comment by jas-** [comment]
Ok, could you go ahead and disclose it on this forum so I may address it. Thanks.

**Comment by jas-** [comment]
@lirantel could you please respond?

**Comment by jas-** [comment]
Thanks, I appreciate any information you or anyone else can provide to make sure this project isn’t insecure for implementors.

However, I am not really sure that I would consider this a security issue as the context of exploit is already mitigated by the running user of the libnmap application would already have access to commands and the need for an existing account on the system in question in order to initiate such an exploit.

I suppose if someone decided to bind a web app to this tool and ran it as root, but that is absurd to begin with.

Regardless, thanks again. I am sure the move from `.test()` to `.match()` will resolve the issue.

Could you confirm so I may close the issue? Thanks.

**Comment by lirantal** [comment]
Hi Jas,

I'm not sure I understand what you mean by mitigation or why it's irrelevant.

Let's say someone is building a CLI ontop of your lib, or say a web UI. They allow users to provide input as range. If that range is not sanitized and can cause command execution how is it not a vulnerability? Are you expecting to put this responsibility of sanitizing user input passed to options on the user? If so why? I would expect that from something like an exec() command that is clearly doing that, but not from this kind of library.

**Comment by jas-** [comment]
Which is why in that same discussion I brought up the use case of binding this to a web application which 1 shouldn't run as root and 2 would be mitigated by the running users restrictions. But yes I would expect web app devs to sanitize input but does not negate the finding you informed me of either.

Regardless, thank you again for finding this. Was a CVE ever assigned? Were you able to verify confirm with the problem fixed with version `v0.1.14`?

**Comment by lirantal** [comment]
Sounds good. I'll request a CVE accordingly that recognizes 0.4.16 as the upgrade path.
Thanks @jas-

**Comment by jas-** [comment]
@lirantal Could you provide the CVE so I can ensure a message is presented for older versions on why they should upgrade? Thanks.

**Comment by lirantal** [comment]
Yep. Already requested one when I closed the report with your 0.4.16 fix.
It takes a bit until it gets approved by HackerOne and then assigned by MITRE so just follow-up on the hackerone report that is public now and you should see the CVE assigned soon (I estimate in a few weeks).
